# Generated by Django 5.0 on 2023-12-16 11:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdoptionDog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adoption_date', models.DateField(blank=True, null=True)),
                ('reason', models.CharField(blank=True, max_length=255, null=True)),
                ('is_adopted', models.BooleanField(blank=True, null=True)),
                ('is_ready_for_adoption', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'adoption_data',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AdoptionOwner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(blank=True, max_length=255, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('relocation_place', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'adoption_owners_data',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BorrowDog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_taking', models.DateField(blank=True, null=True)),
                ('date_of_giving_back', models.DateField(blank=True, null=True)),
                ('note', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'borrow_data',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BorrowPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(blank=True, max_length=255, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'borrow_person_data',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Dog',
            fields=[
                ('dog_id', models.AutoField(primary_key=True, serialize=False)),
                ('photo', models.BinaryField(blank=True, editable=True, null=True)),
                ('dogs_name', models.CharField(blank=True, max_length=255, null=True)),
                ('birth_date', models.DateField()),
                ('gender', models.CharField(blank=True, max_length=10, null=True)),
                ('pool', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'dogs_data',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DogPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'dogs_position',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='InjuryMedicalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('injury_date', models.DateField()),
                ('vet_checkup_needed', models.BooleanField(blank=True, null=True)),
                ('injury_place', models.CharField(blank=True, max_length=255, null=True)),
                ('drugs_name', models.CharField(blank=True, max_length=255, null=True)),
                ('drugs_time_in_days', models.IntegerField(blank=True, null=True)),
                ('stays_in', models.BooleanField(blank=True, null=True)),
                ('is_case_closed', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'injury_hospital_data',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='InjuryType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'db_table': 'injury',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=10, unique=True)),
            ],
            options={
                'db_table': 'positions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sibling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'family_siblings',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MedicalRecord',
            fields=[
                ('id', models.OneToOneField(db_column='id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='medical_record', serialize=False, to='dogyard.dog')),
                ('is_neutered', models.BooleanField(blank=True, null=True)),
                ('is_in_rut', models.BooleanField(blank=True, null=True)),
                ('date_of_death', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'basic_hospital_data',
                'managed': False,
            },
        ),
    ]
